### PR TITLE
Add automated frontend build to v2.0dev

### PR DESCRIPTION
**Pull request by mmalecki**
Use [`inline-source` npm package](https://www.npmjs.com/package/inline-source), run `index.html` through it in order to inline all the scripts and styles we wish to bundle.

Extract the `dronebridge.css` into separate file to have it enjoy the same automation.

Run `npm run build` in `frontend_src` in order to build into `../frontend` (considered building into `build/frontend` as well).

Remove unused `meta`-set `content-type` header, as we set one in the ESP32 static server.

I tested the frontend out on this one (without a real FC yet) and it appears to work, no styling changes or JS breakage.

Pending questions: now that `frontend` directory is a build artifact, should we remove it from the repository, and if so, rename `frontend_src` into just `frontend`?

Happy to tweak anything here to your liking :)

### CODE REVIEW

**Comment by seeul8er** [comment]
Looks great, thank you!
Does it make sense to add the [npm build process as part of the cmake build process](https://stackoverflow.com/questions/57804141/run-npm-commands-from-cmake-project) so it gets triggered automatically?

> Pending questions: now that frontend directory is a build artifact, should we remove it from the repository, and if so, rename frontend_src into just frontend?

I agree. Let's move it to the build directory for now ([adjust cmake here to set new relative path](https://github.com/mmalecki/DroneBridge-ESP32/blob/60ee66bd5c88ca9153e4499ab0e469615313ecb0/main/CMakeLists.txt#L8)). We can document the build process in the readme as part of `frontend_src` and in the Wiki.

**Comment by mmalecki** [comment]
> Does it make sense to add the [npm build process as part of the cmake build process](https://stackoverflow.com/questions/57804141/run-npm-commands-from-cmake-project) so it gets triggered automatically?
I think it does! Let me take a stab at it, thanks for linking these resources.

**Comment by mmalecki** [comment]
@seeul8er I think ^ should do it. It rebuilds the frontend on every build, but the build is so quick I don't think it should matter.

**Comment by seeul8er** [comment]
Let's merge! Thank you so much!

**Pull request merged**
